sudo: required
language: php
php:
  - 5.4

env:
  global:
    - TC=apps/dav/tests/travis/litmus-v2
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

addons:
  apt:
    packages:
    - realpath

before_install:
  - bash tests/travis/before_install.sh $DB

install:
  - bash tests/travis/install.sh $DB
  - bash $TC/install.sh $FTPD

script:
  - bash $TC/script.sh

matrix:
  include:
    - php: 5.4
      env: DB=pgsql;TC=apps/dav/tests/travis/litmus-v1
    - php: 5.4
      env: DB=sqlite;TC=apps/dav/tests/travis/carddav
    - php: 5.4
      env: DB=sqlite;TC=apps/dav/tests/travis/caldav
# pure ftp is not working
#    - php: 5.4
#      env: DB=sqlite;TC=apps/files_external_ftp/tests/travis;FTPD=pure-ftpd
    - php: 5.4
      env: DB=sqlite;TC=apps/files_external_ftp/tests/travis;FTPD=proftpd
    - php: 5.4
      env: DB=sqlite;TC=apps/files_external_ftp/tests/travis;FTPD=vsftpd
    - php: 5.4
      env: DB=sqlite;TC=tests/travis/syntax
    - php: 5.5
      env: DB=sqlite;TC=tests/travis/syntax
    - php: 5.6
      env: DB=sqlite;TC=tests/travis/syntax
    - php: 7.0
      env: DB=sqlite;TC=tests/travis/syntax
    - php: 5.4
      env: DB=sqlite;TC=apps/files_external_ftp/tests/travis;FTPD=vsftpd

  fast_finish: true
